Change the CI tests for the agent v2
Signed-off-by: asakiz <asakizin@gmail.com>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -50,15 +50,15 @@ jobs:
             sleep 1
           done
 
-          if [[ "$(echo "entry_point" | socat - UNIX-CONNECT:updatehub-statechange.sock)" != "" ]]; then
-            echo "Unexpected entry_point response"
-            exit 1
-          fi
           if [[ "$(echo "download" | socat - UNIX-CONNECT:updatehub-statechange.sock)" != "cancel" ]]; then
             echo "Unexpected download response"
+            exit 1
+          fi
+          if [[ "$(echo "install" | socat - UNIX-CONNECT:updatehub-statechange.sock)" != "" ]]; then
+            echo "Unexpected install response"
             exit 2
           fi
-          if [[ "$(echo "error foo" | socat - UNIX-CONNECT:updatehub-statechange.sock)" != "" ]]; then
+          if [[ "$(echo "error" | socat - UNIX-CONNECT:updatehub-statechange.sock)" != "" ]]; then
             echo "Unexpected error response"
             exit 3
           fi
@@ -66,4 +66,3 @@ jobs:
             echo "Unexpected reboot response"
             exit 4
           fi
-
